import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/part/Header";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({subsets: ['latin']})

export const metadata = {
  title: "CRUD",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header/>
        <div className="mx-auto max-w-screen-xl px-6 lg:px-8">
        {children}
        <Toaster/>
        </div>
      </body>
    </html>
  );
}
